# Generated by Django 5.0.6 on 2026-06-18 04:42

import django.core.validators
import django.db.models.deletion
import students.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('marks', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('admitted', models.DateField(auto_now_add=True)),
                ('bio', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, default='students/avatar.svg', upload_to='students/photos/')),
                ('resume', models.FileField(blank=True, upload_to='students/resumes/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'docx']), students.models.validate_file_size])),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='students.department')),
            ],
            options={
                'ordering': ['-marks'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('students', models.ManyToManyField(related_name='courses', to='students.student')),
            ],
        ),
    ]
