# Generated by Django 5.0.6 on 2026-06-18 05:05

import django.core.validators
import students.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='students/resumes/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'docx']), students.models.validate_file_size]),
        ),
    ]
